load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "Social",
    srcs = glob(["Sources/**/*.swift"]),
    module_name = "Social",
    tags = ["manual"],
    visibility = ["//visibility:public"],
    deps = [],
)
